using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using RemTool.Shared;

#nullable disable

namespace RemTool.Shared.Migrations
{
    /// <summary>
    /// La entidad ya estaba en el snapshot de EF, pero no estaba incluida en
    /// db/init.sql ni tenía una migración ejecutable para instalaciones existentes.
    /// </summary>
    [DbContext(typeof(RemToolDataContext))]
    [Migration("20260901120000_AddFiltroEstablecimiento")]
    public partial class AddFiltroEstablecimiento : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""REMTool"".filtro_establecimiento (
                    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    id_establecimiento bigint NOT NULL,
                    id_indicador integer NULL,
                    tipo integer NOT NULL,
                    CONSTRAINT pk_filtro_establecimiento PRIMARY KEY (id)
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ix_filtro_establecimiento_global
                    ON ""REMTool"".filtro_establecimiento (id_establecimiento)
                    WHERE id_indicador IS NULL;

                CREATE UNIQUE INDEX IF NOT EXISTS ix_filtro_establecimiento_indicador
                    ON ""REMTool"".filtro_establecimiento (id_establecimiento, id_indicador)
                    WHERE id_indicador IS NOT NULL;

                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'fk_filtro_establecimiento_establecimiento') THEN
                        ALTER TABLE ""REMTool"".filtro_establecimiento
                            ADD CONSTRAINT fk_filtro_establecimiento_establecimiento
                            FOREIGN KEY (id_establecimiento)
                            REFERENCES ""REMTool"".establecimiento(id) ON DELETE CASCADE;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint
                        WHERE conname = 'fk_filtro_establecimiento_indicador') THEN
                        ALTER TABLE ""REMTool"".filtro_establecimiento
                            ADD CONSTRAINT fk_filtro_establecimiento_indicador
                            FOREIGN KEY (id_indicador)
                            REFERENCES ""REMTool"".indicador(id) ON DELETE CASCADE;
                    END IF;
                END $$;
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS ""REMTool"".filtro_establecimiento;
            ");
        }
    }
}
