// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemTool.Shared;

#nullable disable

namespace RemTool.Shared.Migrations
{
    [DbContext(typeof(RemToolDataContext))]
    partial class RemToolDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RemTool.Shared.CeldaSeccionRem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".celda_seccion_rem_id_seq'::regclass)");

                    b.Property<string>("CeldaBase")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("celda_base");

                    b.Property<string>("CeldaDiccionario")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("celda_diccionario");

                    b.Property<int>("ColSpan")
                        .HasColumnType("integer")
                        .HasColumnName("col_span");

                    b.Property<string>("ColorFondo")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("color_fondo");

                    b.Property<int>("ColumnaOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("columna_origen");

                    b.Property<string>("DependenciasTotal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dependencias_total");

                    b.Property<bool>("EsCeldaAncla")
                        .HasColumnType("boolean")
                        .HasColumnName("es_celda_ancla");

                    b.Property<bool>("EsEditable")
                        .HasColumnType("boolean")
                        .HasColumnName("es_editable");

                    b.Property<bool>("EsEntradaPrestacion")
                        .HasColumnType("boolean")
                        .HasColumnName("es_entrada_prestacion");

                    b.Property<bool>("EsTotal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_total");

                    b.Property<int>("EstiloOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("estilo_origen");

                    b.Property<int>("FilaOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("fila_origen");

                    b.Property<string>("FormulaOrigen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formula_origen");

                    b.Property<int>("IdFila")
                        .HasColumnType("integer")
                        .HasColumnName("id_fila");

                    b.Property<string>("OperacionTotal")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("operacion_total");

                    b.Property<int>("RowSpan")
                        .HasColumnType("integer")
                        .HasColumnName("row_span");

                    b.Property<string>("TipoTotal")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("tipo_total");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdFila");

                    b.ToTable("celda_seccion_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Comuna", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodDeis")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("cod_deis");

                    b.Property<long>("IdServicio")
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id_servicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("comuna", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Convenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".convenio_id_seq'::regclass)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("convenio", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.CoordenadaPrestacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".coordenada_prestacion_id_seq'::regclass)");

                    b.Property<string>("CeldaBase")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("celda_base");

                    b.Property<string>("CeldaDiccionario")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("celda_diccionario");

                    b.Property<string>("CodigoColumna")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("codigo_columna");

                    b.Property<int>("IdCelda")
                        .HasColumnType("integer")
                        .HasColumnName("id_celda");

                    b.Property<int>("IdPrestacion")
                        .HasColumnType("integer")
                        .HasColumnName("id_prestacion");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("IdCelda")
                        .IsUnique();

                    b.HasIndex("IdPrestacion", "Orden")
                        .IsUnique();

                    b.ToTable("coordenada_prestacion", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Establecimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodDeis")
                        .HasColumnType("character varying")
                        .HasColumnName("cod_deis");

                    b.Property<string>("Director")
                        .HasColumnType("character varying")
                        .HasColumnName("director");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<long>("id_sector")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_sector");

                    b.ToTable("establecimiento", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.FilaSeccionRem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".fila_seccion_rem_id_seq'::regclass)");

                    b.Property<int>("FilaOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("fila_origen");

                    b.Property<long>("IdSeccion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_seccion");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<bool>("TienePrestacion")
                        .HasColumnType("boolean")
                        .HasColumnName("tiene_prestacion");

                    b.Property<string>("TipoFila")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("tipo_fila");

                    b.HasKey("Id");

                    b.HasIndex("IdSeccion", "Orden")
                        .IsUnique();

                    b.ToTable("fila_seccion_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.FiltroEstablecimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Tipo")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<long>("id_establecimiento")
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id_establecimiento");

                    b.Property<int?>("id_indicador")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_indicador");

                    b.HasKey("Id");

                    b.HasIndex("id_establecimiento")
                        .IsUnique()
                        .HasFilter("\"id_indicador\" IS NULL");

                    b.HasIndex("id_indicador");

                    b.HasIndex("id_establecimiento", "id_indicador")
                        .IsUnique()
                        .HasFilter("\"id_indicador\" IS NOT NULL");

                    b.ToTable("filtro_establecimiento", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.HojaRem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".hoja_rem_id_seq'::regclass)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("titulo");

                    b.Property<long>("id_serie_rem")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_serie_rem", "Nombre");

                    b.ToTable("hoja_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Indicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".meta_id_seq'::regclass)");

                    b.Property<int>("Año")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("año");

                    b.Property<string>("Detalle")
                        .HasColumnType("character varying")
                        .HasColumnName("detalle");

                    b.Property<bool>("EsPeriodoOctubreSep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_periodo_octubre_sep");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("formula");

                    b.Property<string>("FormulaDenFijo")
                        .HasColumnType("character varying")
                        .HasColumnName("formula_den_fijo");

                    b.Property<bool>("IsColaborativo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_colaborativo");

                    b.Property<bool>("IsDenFijo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_den_fijo");

                    b.Property<bool>("IsTasa")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tasa");

                    b.Property<bool>("Mensual")
                        .HasColumnType("boolean")
                        .HasColumnName("mensual");

                    b.Property<float>("Meta")
                        .HasPrecision(24)
                        .HasColumnType("real")
                        .HasColumnName("meta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<float>("Peso")
                        .HasPrecision(24)
                        .HasColumnType("real")
                        .HasColumnName("peso");

                    b.Property<int?>("Tipoindicador")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_tipoindicador");

                    b.HasKey("Id");

                    b.ToTable("indicador", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.IndicadorConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".indicador_convenio_id_seq'::regclass)");

                    b.Property<int>("id_convenio")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_convenio");

                    b.Property<int>("id_indicador")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_indicador");

                    b.HasKey("Id");

                    b.HasIndex("id_convenio");

                    b.HasIndex("id_indicador");

                    b.ToTable("indicador_convenio", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Informativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contenido");

                    b.Property<bool>("Destacado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("destacado");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("TextoEnlace")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("texto_enlace");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("titulo");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.Property<bool>("Vigente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("vigente");

                    b.HasKey("Id");

                    b.HasIndex("Vigente", "Destacado", "FechaPublicacion");

                    b.ToTable("informativo", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Parametros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("MonitoreoEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("monitoreo_enabled");

                    b.Property<bool>("ServicioEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("servicio_enabled");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("date")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("parametros", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.PercapitaSsc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AñoCorte")
                        .HasColumnType("integer")
                        .HasColumnName("año_corte");

                    b.Property<int>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("edad");

                    b.Property<int>("Inscritos")
                        .HasColumnType("integer")
                        .HasColumnName("inscritos");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("sexo");

                    b.Property<long>("id_establecimiento")
                        .HasColumnType("bigint")
                        .HasColumnName("id_establecimiento");

                    b.HasKey("Id");

                    b.HasIndex("id_establecimiento");

                    b.ToTable("PERCAPITA_SSC", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Prestacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".prestacion_id_seq'::regclass)");

                    b.Property<string>("CodigoPrestacion")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("codigo_prestacion");

                    b.Property<List<string>>("Coordenada")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("coordenada");

                    b.Property<int?>("IdFilaSeccion")
                        .HasColumnType("integer")
                        .HasColumnName("id_fila_seccion");

                    b.Property<long?>("IdSeccion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_seccion");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<int>("id_hoja")
                        .HasColumnType("integer");

                    b.Property<int>("id_version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdFilaSeccion")
                        .IsUnique();

                    b.HasIndex("IdSeccion");

                    b.HasIndex("id_hoja");

                    b.HasIndex("id_version");

                    b.ToTable("prestacion", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.PuntoResumen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("categoria");

                    b.Property<string>("Expresion")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("expresion");

                    b.Property<long>("IdSerieRem")
                        .HasColumnType("bigint")
                        .HasColumnName("id_serie_rem");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("IdSerieRem");

                    b.ToTable("punto_resumen", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".registro_id_seq'::regclass)");

                    b.Property<List<int>>("Valor")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("valor");

                    b.Property<int>("id_prestacion")
                        .HasColumnType("integer");

                    b.Property<int>("id_reporte")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_prestacion");

                    b.HasIndex("id_reporte", "id_prestacion");

                    b.ToTable("registro", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Regla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".regla_id_seq'::regclass)");

                    b.Property<string>("Expresion")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("expresion");

                    b.Property<int>("IdTipoRegla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id_tipo_regla");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("mensaje");

                    b.Property<int>("id_version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoRegla");

                    b.HasIndex("id_version");

                    b.ToTable("regla", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".reporte_id_seq'::regclass)");

                    b.Property<int>("Año")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("año");

                    b.Property<int>("Mes")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<long>("id_comuna")
                        .HasColumnType("bigint");

                    b.Property<long>("id_establecimiento")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_comuna");

                    b.HasIndex("id_establecimiento");

                    b.HasIndex("Año", "Mes", "id_establecimiento");

                    b.ToTable("reporte", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.ResultadoIndicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".resultado_indicador_id_seq'::regclass)");

                    b.Property<decimal>("Denominador")
                        .HasColumnType("numeric")
                        .HasColumnName("denominador");

                    b.Property<decimal>("DenominadorP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("denominador_p");

                    b.Property<int>("Mes")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<decimal>("Numerador")
                        .HasColumnType("numeric")
                        .HasColumnName("numerador");

                    b.Property<decimal>("NumeradorP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("numerador_p");

                    b.Property<long>("id_establecimiento")
                        .HasColumnType("bigint");

                    b.Property<int>("id_indicador")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_establecimiento");

                    b.HasIndex("id_indicador");

                    b.ToTable("resultado_indicador", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.SeccionRem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".seccion_rem_id_seq'::regclass)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("codigo");

                    b.Property<int>("ColumnaFin")
                        .HasColumnType("integer")
                        .HasColumnName("columna_fin");

                    b.Property<int>("ColumnaInicio")
                        .HasColumnType("integer")
                        .HasColumnName("columna_inicio");

                    b.Property<int>("FilaFin")
                        .HasColumnType("integer")
                        .HasColumnName("fila_fin");

                    b.Property<int>("FilaInicio")
                        .HasColumnType("integer")
                        .HasColumnName("fila_inicio");

                    b.Property<string>("HtmlEstructura")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("html_estructura");

                    b.Property<long>("IdHojaRem")
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id_hoja_rem");

                    b.Property<int?>("IdVersionHoja")
                        .HasColumnType("integer")
                        .HasColumnName("id_version_hoja");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<int>("OffsetColumna")
                        .HasColumnType("integer")
                        .HasColumnName("offset_columna");

                    b.Property<int>("OffsetPrestacion")
                        .HasColumnType("integer")
                        .HasColumnName("offset_prestacion");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("RangoBase")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("rango_base");

                    b.Property<string>("RangoDiccionario")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("rango_diccionario");

                    b.HasKey("Id");

                    b.HasIndex("IdVersionHoja", "Orden")
                        .IsUnique();

                    b.ToTable("seccion_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.Sector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("sector", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.SerieRem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("serie_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.TipoIndicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".tipo_indicador_id_seq'::regclass)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipo_indicador", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.TipoRegla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".tipo_regla_id_seq'::regclass)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipo_regla", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.VersionHojaRem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".version_hoja_rem_id_seq'::regclass)");

                    b.Property<int>("IdHoja")
                        .HasColumnType("integer")
                        .HasColumnName("id_hoja");

                    b.Property<int>("IdVersion")
                        .HasColumnType("integer")
                        .HasColumnName("id_version");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("IdHoja");

                    b.HasIndex("IdVersion", "IdHoja")
                        .IsUnique();

                    b.ToTable("version_hoja_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.VersionRem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".version_rem_id_seq'::regclass)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<long>("id_serie")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_serie", "Nombre");

                    b.ToTable("version_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.Shared.CeldaSeccionRem", b =>
                {
                    b.HasOne("RemTool.Shared.FilaSeccionRem", "Fila")
                        .WithMany("Celdas")
                        .HasForeignKey("IdFila")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fila");
                });

            modelBuilder.Entity("RemTool.Shared.CoordenadaPrestacion", b =>
                {
                    b.HasOne("RemTool.Shared.CeldaSeccionRem", "Celda")
                        .WithOne("CoordenadaPrestacion")
                        .HasForeignKey("RemTool.Shared.CoordenadaPrestacion", "IdCelda")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.Shared.Prestacion", "Prestacion")
                        .WithMany("Coordenadas")
                        .HasForeignKey("IdPrestacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Celda");

                    b.Navigation("Prestacion");
                });

            modelBuilder.Entity("RemTool.Shared.Establecimiento", b =>
                {
                    b.HasOne("RemTool.Shared.Sector", "Sector")
                        .WithMany("Establecimientos")
                        .HasForeignKey("id_sector")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("RemTool.Shared.FilaSeccionRem", b =>
                {
                    b.HasOne("RemTool.Shared.SeccionRem", "Seccion")
                        .WithMany("Filas")
                        .HasForeignKey("IdSeccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("RemTool.Shared.FiltroEstablecimiento", b =>
                {
                    b.HasOne("RemTool.Shared.Establecimiento", "Establecimiento")
                        .WithMany("FiltrosEstablecimiento")
                        .HasForeignKey("id_establecimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemTool.Shared.Indicador", "Indicador")
                        .WithMany("FiltrosEstablecimiento")
                        .HasForeignKey("id_indicador")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Establecimiento");

                    b.Navigation("Indicador");
                });

            modelBuilder.Entity("RemTool.Shared.HojaRem", b =>
                {
                    b.HasOne("RemTool.Shared.SerieRem", "SerieRem")
                        .WithMany("HojaRems")
                        .HasForeignKey("id_serie_rem")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SerieRem");
                });

            modelBuilder.Entity("RemTool.Shared.IndicadorConvenio", b =>
                {
                    b.HasOne("RemTool.Shared.Convenio", "Convenio")
                        .WithMany("IndicadorConvenios")
                        .HasForeignKey("id_convenio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemTool.Shared.Indicador", "Indicador")
                        .WithMany("IndicadorConvenios")
                        .HasForeignKey("id_indicador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");

                    b.Navigation("Indicador");
                });

            modelBuilder.Entity("RemTool.Shared.PercapitaSsc", b =>
                {
                    b.HasOne("RemTool.Shared.Establecimiento", "Establecimiento")
                        .WithMany()
                        .HasForeignKey("id_establecimiento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("RemTool.Shared.Prestacion", b =>
                {
                    b.HasOne("RemTool.Shared.FilaSeccionRem", "FilaSeccion")
                        .WithOne("Prestacion")
                        .HasForeignKey("RemTool.Shared.Prestacion", "IdFilaSeccion")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RemTool.Shared.SeccionRem", "Seccion")
                        .WithMany("Prestacions")
                        .HasForeignKey("IdSeccion")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RemTool.Shared.HojaRem", "HojaRem")
                        .WithMany("Prestacions")
                        .HasForeignKey("id_hoja")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.Shared.VersionRem", "VersionRem")
                        .WithMany("Prestacions")
                        .HasForeignKey("id_version")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FilaSeccion");

                    b.Navigation("HojaRem");

                    b.Navigation("Seccion");

                    b.Navigation("VersionRem");
                });

            modelBuilder.Entity("RemTool.Shared.PuntoResumen", b =>
                {
                    b.HasOne("RemTool.Shared.SerieRem", "SerieRem")
                        .WithMany("PuntosResumen")
                        .HasForeignKey("IdSerieRem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SerieRem");
                });

            modelBuilder.Entity("RemTool.Shared.Registro", b =>
                {
                    b.HasOne("RemTool.Shared.Prestacion", "Prestacion")
                        .WithMany("Registros")
                        .HasForeignKey("id_prestacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.Shared.Reporte", "Reporte")
                        .WithMany("Registros")
                        .HasForeignKey("id_reporte")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Prestacion");

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("RemTool.Shared.Regla", b =>
                {
                    b.HasOne("RemTool.Shared.TipoRegla", "TipoRegla")
                        .WithMany("Reglas")
                        .HasForeignKey("IdTipoRegla")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.Shared.VersionRem", "VersionREM")
                        .WithMany("Reglas")
                        .HasForeignKey("id_version")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TipoRegla");

                    b.Navigation("VersionREM");
                });

            modelBuilder.Entity("RemTool.Shared.Reporte", b =>
                {
                    b.HasOne("RemTool.Shared.Comuna", "Comuna")
                        .WithMany("Reportes")
                        .HasForeignKey("id_comuna")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.Shared.Establecimiento", "Establecimiento")
                        .WithMany("Reportes")
                        .HasForeignKey("id_establecimiento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comuna");

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("RemTool.Shared.ResultadoIndicador", b =>
                {
                    b.HasOne("RemTool.Shared.Establecimiento", "Establecimiento")
                        .WithMany("ResultadoIndicadors")
                        .HasForeignKey("id_establecimiento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.Shared.Indicador", "Indicador")
                        .WithMany("ResultadoIndicadors")
                        .HasForeignKey("id_indicador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Establecimiento");

                    b.Navigation("Indicador");
                });

            modelBuilder.Entity("RemTool.Shared.SeccionRem", b =>
                {
                    b.HasOne("RemTool.Shared.VersionHojaRem", "VersionHoja")
                        .WithMany("Secciones")
                        .HasForeignKey("IdVersionHoja")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("VersionHoja");
                });

            modelBuilder.Entity("RemTool.Shared.VersionHojaRem", b =>
                {
                    b.HasOne("RemTool.Shared.HojaRem", "HojaRem")
                        .WithMany("Versiones")
                        .HasForeignKey("IdHoja")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.Shared.VersionRem", "VersionRem")
                        .WithMany("Hojas")
                        .HasForeignKey("IdVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HojaRem");

                    b.Navigation("VersionRem");
                });

            modelBuilder.Entity("RemTool.Shared.VersionRem", b =>
                {
                    b.HasOne("RemTool.Shared.SerieRem", "SerieRem")
                        .WithMany("VersionRems")
                        .HasForeignKey("id_serie")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SerieRem");
                });

            modelBuilder.Entity("RemTool.Shared.CeldaSeccionRem", b =>
                {
                    b.Navigation("CoordenadaPrestacion");
                });

            modelBuilder.Entity("RemTool.Shared.Comuna", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("RemTool.Shared.Convenio", b =>
                {
                    b.Navigation("IndicadorConvenios");
                });

            modelBuilder.Entity("RemTool.Shared.Establecimiento", b =>
                {
                    b.Navigation("FiltrosEstablecimiento");

                    b.Navigation("Reportes");

                    b.Navigation("ResultadoIndicadors");
                });

            modelBuilder.Entity("RemTool.Shared.FilaSeccionRem", b =>
                {
                    b.Navigation("Celdas");

                    b.Navigation("Prestacion");
                });

            modelBuilder.Entity("RemTool.Shared.HojaRem", b =>
                {
                    b.Navigation("Prestacions");

                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("RemTool.Shared.Indicador", b =>
                {
                    b.Navigation("FiltrosEstablecimiento");

                    b.Navigation("IndicadorConvenios");

                    b.Navigation("ResultadoIndicadors");
                });

            modelBuilder.Entity("RemTool.Shared.Prestacion", b =>
                {
                    b.Navigation("Coordenadas");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("RemTool.Shared.Reporte", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("RemTool.Shared.SeccionRem", b =>
                {
                    b.Navigation("Filas");

                    b.Navigation("Prestacions");
                });

            modelBuilder.Entity("RemTool.Shared.Sector", b =>
                {
                    b.Navigation("Establecimientos");
                });

            modelBuilder.Entity("RemTool.Shared.SerieRem", b =>
                {
                    b.Navigation("HojaRems");

                    b.Navigation("PuntosResumen");

                    b.Navigation("VersionRems");
                });

            modelBuilder.Entity("RemTool.Shared.TipoRegla", b =>
                {
                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("RemTool.Shared.VersionHojaRem", b =>
                {
                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("RemTool.Shared.VersionRem", b =>
                {
                    b.Navigation("Hojas");

                    b.Navigation("Prestacions");

                    b.Navigation("Reglas");
                });
#pragma warning restore 612, 618
        }
    }
}
