// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemTool;

#nullable disable

namespace RemTool.Dal.Migrations
{
    [DbContext(typeof(VoidDataContext))]
    partial class VoidDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RemTool.Comuna", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodDeis")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("cod_deis");

                    b.Property<long>("IdServicio")
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id_servicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("comuna", "REMTool");
                });

            modelBuilder.Entity("RemTool.Establecimiento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodDeis")
                        .HasColumnType("character varying")
                        .HasColumnName("cod_deis");

                    b.Property<string>("Director")
                        .HasColumnType("character varying")
                        .HasColumnName("director");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<long>("id_sector")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_sector");

                    b.ToTable("establecimiento", "REMTool");
                });

            modelBuilder.Entity("RemTool.HojaRem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".hoja_rem_id_seq'::regclass)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<long>("id_serie_rem")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_serie_rem");

                    b.ToTable("hoja_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.Indicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".meta_id_seq'::regclass)");

                    b.Property<int>("Año")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("año");

                    b.Property<bool>("DesplazarDenominador3Meses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("desplazar_denominador_3_meses");

                    b.Property<string>("Detalle")
                        .HasColumnType("character varying")
                        .HasColumnName("detalle");

                    b.Property<bool>("EsPeriodoOctubreSep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_periodo_octubre_sep");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("formula");

                    b.Property<string>("FormulaDenFijo")
                        .HasColumnType("character varying")
                        .HasColumnName("formula_den_fijo");

                    b.Property<bool>("IsDenFijo")
                        .HasColumnType("boolean")
                        .HasColumnName("is_den_fijo");

                    b.Property<bool>("IsTasa")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tasa");

                    b.Property<bool>("Mensual")
                        .HasColumnType("boolean")
                        .HasColumnName("mensual");

                    b.Property<float>("Meta")
                        .HasPrecision(24)
                        .HasColumnType("real")
                        .HasColumnName("meta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<float>("Peso")
                        .HasPrecision(24)
                        .HasColumnType("real")
                        .HasColumnName("peso");

                    b.Property<int?>("Tipoindicador")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id_tipoindicador");

                    b.HasKey("Id");

                    b.ToTable("indicador", "REMTool");
                });

            modelBuilder.Entity("RemTool.Parametros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ServicioEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("servicio_enabled");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("date")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("Id");

                    b.ToTable("parametros", "REMTool");
                });

            modelBuilder.Entity("RemTool.Prestacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".prestacion_id_seq'::regclass)");

                    b.Property<string>("CodigoPrestacion")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("codigo_prestacion");

                    b.Property<List<string>>("Coordenada")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("coordenada");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("id_hoja")
                        .HasColumnType("integer");

                    b.Property<int>("id_version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_hoja");

                    b.HasIndex("id_version");

                    b.ToTable("prestacion", "REMTool");
                });

            modelBuilder.Entity("RemTool.Registro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".registro_id_seq'::regclass)");

                    b.Property<List<int>>("Valor")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("valor");

                    b.Property<int>("id_prestacion")
                        .HasColumnType("integer");

                    b.Property<int>("id_reporte")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_prestacion");

                    b.HasIndex("id_reporte");

                    b.ToTable("registro", "REMTool");
                });

            modelBuilder.Entity("RemTool.Regla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".regla_id_seq'::regclass)");

                    b.Property<string>("Expresion")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("expresion");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("mensaje");

                    b.Property<int>("id_version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_version");

                    b.ToTable("regla", "REMTool");
                });

            modelBuilder.Entity("RemTool.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".reporte_id_seq'::regclass)");

                    b.Property<int>("Mes")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<long>("id_comuna")
                        .HasColumnType("bigint");

                    b.Property<long>("id_establecimiento")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_comuna");

                    b.HasIndex("id_establecimiento");

                    b.ToTable("reporte", "REMTool");
                });

            modelBuilder.Entity("RemTool.ResultadoIndicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".resultado_indicador_id_seq'::regclass)");

                    b.Property<decimal>("Denominador")
                        .HasColumnType("numeric")
                        .HasColumnName("denominador");

                    b.Property<int>("Mes")
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<decimal>("Numerador")
                        .HasColumnType("numeric")
                        .HasColumnName("numerador");

                    b.Property<long>("id_establecimiento")
                        .HasColumnType("bigint");

                    b.Property<int>("id_indicador")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("id_establecimiento");

                    b.HasIndex("id_indicador");

                    b.ToTable("resultado_indicador", "REMTool");
                });

            modelBuilder.Entity("RemTool.SeccionRem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("IdHojaRem")
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id_hoja_rem");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("seccion_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.Sector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("sector", "REMTool");
                });

            modelBuilder.Entity("RemTool.SerieRem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(64)
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("serie_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.TipoIndicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".tipo_indicador_id_seq'::regclass)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("tipo_indicador", "REMTool");
                });

            modelBuilder.Entity("RemTool.VersionRem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(32)
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValueSql("nextval('\"REMTool\".version_rem_id_seq'::regclass)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nombre");

                    b.Property<long>("id_serie")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("id_serie");

                    b.ToTable("version_rem", "REMTool");
                });

            modelBuilder.Entity("RemTool.Establecimiento", b =>
                {
                    b.HasOne("RemTool.Sector", "Sector")
                        .WithMany("Establecimientos")
                        .HasForeignKey("id_sector")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("RemTool.HojaRem", b =>
                {
                    b.HasOne("RemTool.SerieRem", "SerieRem")
                        .WithMany("HojaRems")
                        .HasForeignKey("id_serie_rem")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SerieRem");
                });

            modelBuilder.Entity("RemTool.Prestacion", b =>
                {
                    b.HasOne("RemTool.HojaRem", "HojaRem")
                        .WithMany("Prestacions")
                        .HasForeignKey("id_hoja")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.VersionRem", "VersionRem")
                        .WithMany("Prestacions")
                        .HasForeignKey("id_version")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HojaRem");

                    b.Navigation("VersionRem");
                });

            modelBuilder.Entity("RemTool.Registro", b =>
                {
                    b.HasOne("RemTool.Prestacion", "Prestacion")
                        .WithMany("Registros")
                        .HasForeignKey("id_prestacion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.Reporte", "Reporte")
                        .WithMany("Registros")
                        .HasForeignKey("id_reporte")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Prestacion");

                    b.Navigation("Reporte");
                });

            modelBuilder.Entity("RemTool.Regla", b =>
                {
                    b.HasOne("RemTool.VersionRem", "VersionREM")
                        .WithMany("Reglas")
                        .HasForeignKey("id_version")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("VersionREM");
                });

            modelBuilder.Entity("RemTool.Reporte", b =>
                {
                    b.HasOne("RemTool.Comuna", "Comuna")
                        .WithMany("Reportes")
                        .HasForeignKey("id_comuna")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.Establecimiento", "Establecimiento")
                        .WithMany("Reportes")
                        .HasForeignKey("id_establecimiento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comuna");

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("RemTool.ResultadoIndicador", b =>
                {
                    b.HasOne("RemTool.Establecimiento", "Establecimiento")
                        .WithMany("ResultadoIndicadors")
                        .HasForeignKey("id_establecimiento")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RemTool.Indicador", "Indicador")
                        .WithMany("ResultadoIndicadors")
                        .HasForeignKey("id_indicador")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Establecimiento");

                    b.Navigation("Indicador");
                });

            modelBuilder.Entity("RemTool.VersionRem", b =>
                {
                    b.HasOne("RemTool.SerieRem", "SerieRem")
                        .WithMany("VersionRems")
                        .HasForeignKey("id_serie")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SerieRem");
                });

            modelBuilder.Entity("RemTool.Comuna", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("RemTool.Establecimiento", b =>
                {
                    b.Navigation("Reportes");

                    b.Navigation("ResultadoIndicadors");
                });

            modelBuilder.Entity("RemTool.HojaRem", b =>
                {
                    b.Navigation("Prestacions");
                });

            modelBuilder.Entity("RemTool.Indicador", b =>
                {
                    b.Navigation("ResultadoIndicadors");
                });

            modelBuilder.Entity("RemTool.Prestacion", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("RemTool.Reporte", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("RemTool.Sector", b =>
                {
                    b.Navigation("Establecimientos");
                });

            modelBuilder.Entity("RemTool.SerieRem", b =>
                {
                    b.Navigation("HojaRems");

                    b.Navigation("VersionRems");
                });

            modelBuilder.Entity("RemTool.VersionRem", b =>
                {
                    b.Navigation("Prestacions");

                    b.Navigation("Reglas");
                });
#pragma warning restore 612, 618
        }
    }
}
