using Microsoft.EntityFrameworkCore;
using RemTool.Shared;

public static class AdminCrudRoutes
{
    public static void MapCrud(this RouteGroupBuilder api)
    {
        api.MapGet("/catalog", async (RemToolDataContext db, CancellationToken ct) => Results.Ok(new {
            series = await db.SerieRem.AsNoTracking().OrderBy(x => x.Nombre).Select(x => new { x.Id, x.Nombre }).ToListAsync(ct),
            versions = await db.VersionRem.AsNoTracking().Include(x => x.SerieRem).OrderByDescending(x => x.Fecha).Select(x => new { x.Id, x.Nombre, x.Fecha, serie = x.SerieRem.Nombre }).ToListAsync(ct),
            ruleTypes = await db.TipoRegla.AsNoTracking().OrderBy(x => x.Nombre).Select(x => new { x.Id, x.Nombre }).ToListAsync(ct),
            establishments = await db.Establecimiento.AsNoTracking().OrderBy(x => x.Nombre).Select(x => new { x.Id, x.Nombre, x.CodDeis }).ToListAsync(ct),
            indicators = await db.Indicador.AsNoTracking().OrderByDescending(x => x.Año).ThenBy(x => x.Orden).Select(x => new { x.Id, x.Nombre, x.Año }).ToListAsync(ct)
        }));
        api.MapGet("/rules", async (RemToolDataContext db, CancellationToken ct) => Results.Ok(await db.Regla.AsNoTracking().Include(x => x.TipoRegla).Include(x => x.VersionREM).ThenInclude(x => x.SerieRem).OrderBy(x => x.Id).Select(x => new { x.Id, x.id_version, x.IdTipoRegla, x.Expresion, x.Mensaje, version = x.VersionREM.Nombre, serie = x.VersionREM.SerieRem.Nombre, tipo = x.TipoRegla.Nombre }).ToListAsync(ct)));
        api.MapPost("/rules", async (RuleCommand command, RemToolDataContext db, CancellationToken ct) => { Validate(command.Expresion, command.Mensaje); var x = new Regla { id_version = command.VersionId, IdTipoRegla = command.RuleTypeId, Expresion = command.Expresion.Trim(), Mensaje = command.Mensaje.Trim() }; db.Add(x); await db.SaveChangesAsync(ct); return Results.Ok(new { x.Id }); });
        api.MapPut("/rules/{id:int}", async (int id, RuleCommand command, RemToolDataContext db, CancellationToken ct) => { Validate(command.Expresion, command.Mensaje); var x = await db.Regla.FindAsync([id], ct) ?? throw new KeyNotFoundException("Regla no encontrada."); x.id_version = command.VersionId; x.IdTipoRegla = command.RuleTypeId; x.Expresion = command.Expresion.Trim(); x.Mensaje = command.Mensaje.Trim(); await db.SaveChangesAsync(ct); return Results.NoContent(); });
        api.MapDelete("/rules/{id:int}", async (int id, RemToolDataContext db, CancellationToken ct) => { var x = await db.Regla.FindAsync([id], ct) ?? throw new KeyNotFoundException("Regla no encontrada."); db.Remove(x); await db.SaveChangesAsync(ct); return Results.NoContent(); });
        api.MapGet("/summary-points", async (RemToolDataContext db, CancellationToken ct) => Results.Ok(await db.PuntoResumen.AsNoTracking().Include(x => x.SerieRem).OrderBy(x => x.Categoria).ThenBy(x => x.Nombre).Select(x => new { x.Id, x.Nombre, x.Categoria, x.Expresion, x.IdSerieRem, serie = x.SerieRem.Nombre }).ToListAsync(ct)));
        api.MapPost("/summary-points", async (SummaryPointCommand command, RemToolDataContext db, CancellationToken ct) => { Validate(command.Nombre, command.Expresion); var x = new PuntoResumen { Nombre = command.Nombre.Trim(), Categoria = command.Categoria.Trim(), Expresion = command.Expresion.Trim(), IdSerieRem = command.SeriesId }; db.Add(x); await db.SaveChangesAsync(ct); return Results.Ok(new { x.Id }); });
        api.MapPut("/summary-points/{id:int}", async (int id, SummaryPointCommand command, RemToolDataContext db, CancellationToken ct) => { Validate(command.Nombre, command.Expresion); var x = await db.PuntoResumen.FindAsync([id], ct) ?? throw new KeyNotFoundException("Punto no encontrado."); x.Nombre = command.Nombre.Trim(); x.Categoria = command.Categoria.Trim(); x.Expresion = command.Expresion.Trim(); x.IdSerieRem = command.SeriesId; await db.SaveChangesAsync(ct); return Results.NoContent(); });
        api.MapDelete("/summary-points/{id:int}", async (int id, RemToolDataContext db, CancellationToken ct) => { var x = await db.PuntoResumen.FindAsync([id], ct) ?? throw new KeyNotFoundException("Punto no encontrado."); db.Remove(x); await db.SaveChangesAsync(ct); return Results.NoContent(); });
        api.MapGet("/reports", async (int? year, int? month, string? search, RemToolDataContext db, CancellationToken ct) => { var q = db.Reporte.AsNoTracking().Include(x => x.Establecimiento).Include(x => x.Comuna).AsQueryable(); if (year.HasValue) q = q.Where(x => x.Año == year); if (month.HasValue) q = q.Where(x => x.Mes == month); if (!string.IsNullOrWhiteSpace(search)) q = q.Where(x => x.Establecimiento.Nombre.Contains(search)); return Results.Ok(await q.OrderByDescending(x => x.Año).ThenByDescending(x => x.Mes).Take(500).Select(x => new { x.Id, x.Año, x.Mes, establecimiento = x.Establecimiento.Nombre, comuna = x.Comuna.Nombre, records = x.Registros.Count }).ToListAsync(ct)); });
        api.MapGet("/reports/{id:int}/records", async (int id, RemToolDataContext db, CancellationToken ct) => Results.Ok(await db.Registro.AsNoTracking().Where(x => x.id_reporte == id).Include(x => x.Prestacion).OrderBy(x => x.Prestacion.CodigoPrestacion).Select(x => new { x.Id, code = x.Prestacion.CodigoPrestacion, x.Valor }).ToListAsync(ct)));
        api.MapDelete("/reports/{id:int}", async (int id, RemToolDataContext db, CancellationToken ct) => { var x = await db.Reporte.FindAsync([id], ct) ?? throw new KeyNotFoundException("Reporte no encontrado."); await db.Registro.Where(r => r.id_reporte == id).ExecuteDeleteAsync(ct); db.Remove(x); await db.SaveChangesAsync(ct); return Results.NoContent(); });
        api.MapGet("/convenios", async (RemToolDataContext db, CancellationToken ct) => Results.Ok(await db.Convenio.AsNoTracking().Include(x => x.IndicadorConvenios).OrderBy(x => x.Nombre).Select(x => new { x.Id, x.Nombre, indicatorIds = x.IndicadorConvenios.Select(y => y.id_indicador) }).ToListAsync(ct)));
        api.MapPost("/convenios", async (ConvenioCommand command, RemToolDataContext db, CancellationToken ct) => Results.Ok(new { id = await SaveConvenio(null, command, db, ct) }));
        api.MapPut("/convenios/{id:int}", async (int id, ConvenioCommand command, RemToolDataContext db, CancellationToken ct) => { await SaveConvenio(id, command, db, ct); return Results.NoContent(); });
        api.MapDelete("/convenios/{id:int}", async (int id, RemToolDataContext db, CancellationToken ct) => { var x = await db.Convenio.FindAsync([id], ct) ?? throw new KeyNotFoundException("Convenio no encontrado."); db.Remove(x); await db.SaveChangesAsync(ct); return Results.NoContent(); });
        api.MapGet("/filters", async (RemToolDataContext db, CancellationToken ct) => Results.Ok(await db.FiltroEstablecimiento.AsNoTracking().Include(x => x.Establecimiento).Include(x => x.Indicador).OrderBy(x => x.Id).Select(x => new { x.Id, x.id_establecimiento, x.id_indicador, x.Tipo, establishment = x.Establecimiento.Nombre, indicator = x.Indicador == null ? null : x.Indicador.Nombre }).ToListAsync(ct)));
        api.MapPost("/filters", async (FilterCommand command, RemToolDataContext db, CancellationToken ct) => Results.Ok(new { id = await SaveFilter(null, command, db, ct) }));
        api.MapPut("/filters/{id:int}", async (int id, FilterCommand command, RemToolDataContext db, CancellationToken ct) => { await SaveFilter(id, command, db, ct); return Results.NoContent(); });
        api.MapDelete("/filters/{id:int}", async (int id, RemToolDataContext db, CancellationToken ct) => { var x = await db.FiltroEstablecimiento.FindAsync([id], ct) ?? throw new KeyNotFoundException("Filtro no encontrado."); db.Remove(x); await db.SaveChangesAsync(ct); return Results.NoContent(); });
        api.MapGet("/indicators", async (int? year, RemToolDataContext db, CancellationToken ct) => { var q = db.Indicador.AsNoTracking().AsQueryable(); if (year.HasValue) q = q.Where(x => x.Año == year); return Results.Ok(await q.OrderByDescending(x => x.Año).ThenBy(x => x.Orden).Select(x => new { x.Id, x.Nombre, x.Formula, x.Año, x.IsDenFijo, x.IsTasa, x.FormulaDenFijo, x.Meta, x.Peso, x.Mensual, x.Orden, x.Detalle, x.Tipoindicador, x.EsPeriodoOctubreSep, x.IsColaborativo }).ToListAsync(ct)); });
        api.MapPost("/indicators", async (IndicatorCommand command, RemToolDataContext db, CancellationToken ct) => Results.Ok(new { id = await SaveIndicator(null, command, db, ct) }));
        api.MapPut("/indicators/{id:int}", async (int id, IndicatorCommand command, RemToolDataContext db, CancellationToken ct) => { await SaveIndicator(id, command, db, ct); return Results.NoContent(); });
        api.MapDelete("/indicators/{id:int}", async (int id, RemToolDataContext db, CancellationToken ct) => { var x = await db.Indicador.FindAsync([id], ct) ?? throw new KeyNotFoundException("Indicador no encontrado."); db.Remove(x); await db.SaveChangesAsync(ct); return Results.NoContent(); });
    }
    private static void Validate(string first, string second) { if (string.IsNullOrWhiteSpace(first) || string.IsNullOrWhiteSpace(second)) throw new ArgumentException("Los campos obligatorios están vacíos."); }
    private static async Task<int> SaveConvenio(int? id, ConvenioCommand command, RemToolDataContext db, CancellationToken ct) { if (string.IsNullOrWhiteSpace(command.Nombre)) throw new ArgumentException("El nombre es obligatorio."); if (await db.Convenio.AnyAsync(x => x.Id != id && x.Nombre == command.Nombre.Trim(), ct)) throw new ArgumentException("Ya existe un convenio con ese nombre."); var x = id is null ? new Convenio() : await db.Convenio.FindAsync([id.Value], ct) ?? throw new KeyNotFoundException("Convenio no encontrado."); x.Nombre = command.Nombre.Trim(); if (id is null) db.Add(x); await db.SaveChangesAsync(ct); var selected = command.IndicatorIds.Distinct().ToHashSet(); var current = await db.IndicadorConvenio.Where(y => y.id_convenio == x.Id).ToListAsync(ct); db.RemoveRange(current.Where(y => !selected.Contains(y.id_indicador))); foreach (var indicatorId in selected.Except(current.Select(y => y.id_indicador))) db.IndicadorConvenio.Add(new IndicadorConvenio { id_convenio = x.Id, id_indicador = indicatorId }); await db.SaveChangesAsync(ct); return x.Id; }
    private static async Task<int> SaveFilter(int? id, FilterCommand command, RemToolDataContext db, CancellationToken ct) { if (command.IndicatorId is null && command.Tipo == 1) throw new ArgumentException("No se permite una inclusión global."); if (await db.FiltroEstablecimiento.AnyAsync(x => x.Id != id && x.id_establecimiento == command.EstablishmentId && x.id_indicador == command.IndicatorId, ct)) throw new ArgumentException("Ya existe ese filtro."); var x = id is null ? new FiltroEstablecimiento() : await db.FiltroEstablecimiento.FindAsync([id.Value], ct) ?? throw new KeyNotFoundException("Filtro no encontrado."); x.id_establecimiento = command.EstablishmentId; x.id_indicador = command.IndicatorId; x.Tipo = (RemTool.Shared.Enum.TipoFiltroEstablecimiento)command.Tipo; if (id is null) db.Add(x); await db.SaveChangesAsync(ct); return x.Id; }
    private static async Task<int> SaveIndicator(int? id, IndicatorCommand c, RemToolDataContext db, CancellationToken ct) { Validate(c.Nombre, c.Formula); if (c.Year is < 2000 or > 2100) throw new ArgumentException("El año no es válido."); var x = id is null ? new Indicador() : await db.Indicador.FindAsync([id.Value], ct) ?? throw new KeyNotFoundException("Indicador no encontrado."); x.Nombre=c.Nombre.Trim(); x.Formula=c.Formula; x.Año=c.Year; x.IsDenFijo=c.IsDenFijo; x.IsTasa=c.IsTasa; x.FormulaDenFijo=c.FormulaDenFijo; x.Meta=c.Meta; x.Peso=c.Peso; x.Mensual=c.Mensual; x.Orden=c.Orden; x.Detalle=c.Detalle; x.Tipoindicador=c.TipoIndicador; x.EsPeriodoOctubreSep=c.EsPeriodoOctubreSep; x.IsColaborativo=c.IsColaborativo; if (id is null) db.Add(x); await db.SaveChangesAsync(ct); return x.Id; }
}
public sealed record RuleCommand(int VersionId, int RuleTypeId, string Expresion, string Mensaje);
public sealed record SummaryPointCommand(string Nombre, string Categoria, string Expresion, long SeriesId);
public sealed record ConvenioCommand(string Nombre, IReadOnlyList<int> IndicatorIds);
public sealed record FilterCommand(long EstablishmentId, int? IndicatorId, int Tipo);
public sealed record IndicatorCommand(string Nombre, string Formula, int Year, bool IsDenFijo, bool IsTasa, string? FormulaDenFijo, float Meta, float Peso, bool Mensual, int Orden, string? Detalle, int? TipoIndicador, bool EsPeriodoOctubreSep, bool IsColaborativo);
